### ISSUE TITLE
Kernel died when I generate.

### ISSUE THREAD

**Issue by AshleyRm** [smhongok/inv-dpm#1]
Outstanding work!
I am trying to use your perfect work in my work but there is a problem.
![1](https://github.com/smhongok/inv-dpm/assets/95748505/97cdcd07-0262-4769-8757-73c6216c0475)
Thanks for help!

**Comment by AshleyRm** [comment]
I have tried  restart kernel or other choice in jupyter notebook and installed the last version jupyter notebook but it is still not work.

**Comment by smhongok** [comment]
Thanks for trying and sharing the issues.
It seems that sometimes the kernel crashes if your GPU doesn't have enough memory. To run our code smoothly (we're using Stable Diffusion 2.1), you'll need a GPU with at least 16 GB of memory. We've tested it on an NVIDIA RTX 3090Ti with 24GB of memory, and it worked like a charm.

If your GPU meets the memory requirement, it's also a good idea to double-check the versions of dependencies listed in our requirement.txt file.

Thanks again for your efforts!

Best regards,
Seongmin
