### ISSUE TITLE
wandb error

### ISSUE THREAD

**Issue by chbw818** [smhongok/inv-dpm#3]
<img width="974" alt="image" src="https://github.com/smhongok/inv-dpm/assets/128128295/3a8d96c4-b267-4c4c-8edf-bbf291f719ba">
`python main_watermark_detection.py --length 1 --num_inference_steps 10 --inv_order 2 --with_tracking`
When I ran your code with this commands, I met this error.How can i fix it?

**Comment by chbw818** [comment]
Sorry,I know why this error occurs.I also want to know what I should fill in in the 'inference model'

**Comment by smhongok** [comment]
Thanks for sharing.
what is the 'inference model'?
If you are talking about 'reference model',
then, please just leave it to None.

**Comment by chbw818** [comment]
Yes, I made a mistake in writing
But the code is like this:
https://github.com/smhongok/inv-dpm/blob/784e31b2682a1315a30789ae73fbc7dd56da2126/main_watermark_detection.py#L55
and
https://github.com/smhongok/inv-dpm/blob/784e31b2682a1315a30789ae73fbc7dd56da2126/main_watermark_detection.py#L198
so if I leave it None，this error will occur.
So I deleted `(args.reference_model is not None)` and there won't be any errors.

**Comment by smhongok** [comment]
Thanks, we also updated the code. Now reference_model doesn't matter.
