### ISSUE TITLE
RuntimeError: The size of tensor a (8192) must match the size of tensor b (4096) at non-singleton dimension 1

### ISSUE THREAD

**Issue by chbw818** [smhongok/inv-dpm#4]
Great work!
When I set `--prompt_unknown`,this error occurs.
<img width="532" alt="image" src="https://github.com/smhongok/inv-dpm/assets/128128295/1db66728-5311-4b08-9170-0453979f5710">
Could you please tell me how to solve it?or I should always set`--prompt_unknown False`.Thanks!

**Comment by smhongok** [comment]
There was an error in L102-104 of main_watermark_detction.py. We just fixed this issue. Thank you.
